In [63]:
import torch
import numpy as np
import pandas as pd

# Create tensor

In [15]:
array_1d = torch.arange(12, dtype=torch.float32)  
array_1d

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
array_1d.shape
# the output is a vector

torch.Size([12])

In [5]:
array_1d.numel() # number of element
# the output is a scalar (number)

12

In [6]:
array_2d = array_1d.reshape(3,4)
array_2d

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
torch.tensor([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [0,1,2]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0, 1, 2]])

In [33]:
# tensor with random number 
torch.randn(3, 4)

tensor([[-0.2546, -0.3437,  0.1845,  1.0890],
        [-0.5648, -1.3672, -0.2387,  1.6616],
        [-0.7376, -0.0825,  0.9999, -0.6105]])

# Tensor Calculation

Tensor calculation are element-wise

In [22]:
x = torch.tensor([1.0, 2, 4, 8])  # 1.0 will make the tensor as float type
y = torch.tensor([2, 2, 2, 2])

x + y, x - y, x * y, x / y, x ** y  # tensors should be same shape

tensor(4.)


(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [25]:
x.sum()
# sum all elements in a tensor, return a scalar

tensor(15.)

In [23]:
x == y

tensor([False,  True, False, False])

# Tensor Manipulation

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
# concat vertically
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [20]:
# concat horizontally
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

# Broadcast

In [28]:
a = torch.arange(3).reshape(3,1)   # 3 x 1
b = torch.arange(2).reshape(1,2)   # 1 x 2

a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [29]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

**What happened?**       

When adding 3x1 with 1x2, both tensors are stretched into 3x2.             
In essense, the actual tensors being added up are:      
       
a transformed into: (the second column is copied from first column)     
[[0, 0],     
 [1, 1],     
 [2, 2]]      

b transformed into: (the second and third row are copied from the first row)     
[[0, 1],      
 [0, 1],      
 [0, 1]]         

**Rules for Broadcast:**      
For each dimension (**starting from the end**):      

1. If the sizes are equal → ✅ compatible.  Eg: 3x4 + 3x4        

2. If one of them is 1 → ✅ compatible (the size-1 dim is “stretched”). Eg: 3x4 + 1x4

3. If one tensor has fewer dimensions, PyTorch pretends it has leading dimensions of size 1.  Eg:  3x4 + 4 -> 3x4 + 1x4           

4. Otherwise → ❌ broadcasting error. Eg: 3x4 + 6x1       


In [34]:
# Error example

c = torch.arange(12).reshape(3, 4)     # 3x4
d = torch.arange(4).reshape(4, 1)      # 6x1

c + d

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

# Slicing

In [35]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
X[-1]
# get last row

tensor([ 8.,  9., 10., 11.])

In [37]:
X[1:3]
# get second and third row

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

# Modify Tensor

In [38]:
X[1,2] = 9 
X
# Change value at position (1, 2)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
X[0:2, :] = 12
X
# Change value by range

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## BE CAREFUL with Memory Address

In [51]:
before_address = id(Y)
Y = Y + X         # object y is first destructed and then reconstructed
id(Y) == before_address  # False

# This is especially problematic when data is big

False

## Correct way

In [48]:
# Approach 1: 

before_address = id(Y)
Y += X                  # Object Z is not reconstructed. This is different than Z = Z + X
id(Y) == before_address

True

In [49]:
# Approach 2: 

before_address = id(Y)
print('id(Y): ', id(Y))
Y[:] = X + Y            # this limits the modification to tensor elements, not tensor object
print('id(Y): ', id(Y))  # memory address not changed

id(Y):  5980225760
id(Y):  5980225760


# Tensor <-> Array/Scalar

In [57]:
print(type(X))
X

<class 'torch.Tensor'>


tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [58]:
A = X.numpy()
print(type(A))
A

<class 'numpy.ndarray'>


array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [59]:
B = torch.tensor(A)
print(type(B))
B

<class 'torch.Tensor'>


tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [61]:
a = torch.tensor([3.5])
print(type(a))

a, a.item(), float(a), int(a)

<class 'torch.Tensor'>


(tensor([3.5000]), 3.5, 3.5, 3)

# Pandas DF -> Tensor

In [65]:
df = pd.DataFrame({'num_rooms': [np.NaN, 2.0, 4.0, np.NaN], 
                   'alley': ['Pave', np.NaN, np.NaN, np.NaN], 
                   'price': [127500, 106000, 178100, 140000]})
df

num_rooms alley   price
0        NaN  Pave  127500
1        2.0   NaN  106000
2        4.0   NaN  178100
3        NaN   NaN  140000

In [77]:
inputs, outputs = df.iloc[:,0:2], df.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
inputs

num_rooms alley
0        3.0  Pave
1        2.0   NaN
2        4.0   NaN
3        3.0   NaN

In [78]:
inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)
inputs

num_rooms  alley_Pave  alley_nan
0        3.0           1          0
1        2.0           0          1
2        4.0           0          1
3        3.0           0          1

In [79]:
## DF -> Tensor

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [ ]:
# By default, Python will store floats as 64bit. In deep learning, 64 bit is slow to compute, usually use 32 bit. 