In [1]:
import torch

# Scalar Calculation

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

# Vector Calculation

In [3]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

## Inner Product

In [4]:
# Inner Product

y = torch.ones(4, dtype=torch.float32)

print(x)
print(y)
print(torch.dot(x, y))

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)


In [5]:
# Another way of calculating Inner Product
print(x * y)
print(torch.sum(x * y))

tensor([0., 1., 2., 3.])
tensor(6.)


## Norm

In [6]:
# L2 Norm

v = torch.tensor([3.0, -4.0])
torch.norm(v)

tensor(5.)

In [7]:
# L1 Norm

print(v)
print(torch.abs(v).sum())

tensor([ 3., -4.])
tensor(7.)


# Matrix Calculation

In [8]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
# Transpose
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [10]:
# Symmetric Matrix
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## Multiplication

In [12]:
# Matrix multiply Vector

A = torch.arange(20, dtype = torch.float32).reshape(5,4)
x = torch.arange(4, dtype = torch.float32)

print(A, A.shape)
print(x, x.shape)
print(torch.mv(A, x), torch.mv(A, x).shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) torch.Size([5, 4])
tensor([0., 1., 2., 3.]) torch.Size([4])
tensor([ 14.,  38.,  62.,  86., 110.]) torch.Size([5])


In [13]:
# Matrix multiply Matrix

print(A, A.shape)

B = torch.ones(4, 3)
print(B, B.shape)

print(torch.mm(A, B), torch.mm(A, B).shape)  # torch.mm is strictly limited to 2-dim matrix calculation, can't be used on tensors.  

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) torch.Size([5, 4])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])
tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]]) torch.Size([5, 3])


## Frobenius Norm

In [15]:
# Frobenius Norm is the most commonly used norm of Matrices

M = torch.ones(4, 9)    
print(M)
print(torch.norm(M))  # sqrt(sum(square of each element))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor(6.)


# Tensor Calculation

Tensor can be regarded as the generalization of matrices.        
Matrices ususally have 2 dimision (row and column), whereas tensor can have any number of dimisions.     

## Tensor with Scalar

In [16]:
# Add & Multiply scalar to Tensor

a = 2 
X = torch.arange(24).reshape(2,3,4) 

a + X, a * X, (a * X).shape   

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [17]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## Tensor with Tensor

In [18]:
# Add Tensors

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # creates a new object, B is not a reference of A 

A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [32]:
# Multiply Tensors  

C = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)  # batch of 2 matrices, matrices shape = 3x4
D = torch.ones(2, 4, 5)                                     # batch of 2 matrices, matrices shape = 4x5
# batch number have to be same (2), matrices shape must satisfy matrix multiplication (3x4 * 4x5 = 3x5). Result will be 2x3x5

print(C, C.shape)
print(D, D.shape)
print(C @ D, (torch.matmul(C, D).shape))   # '@' is the magic command for torch.matmul()

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]]) torch.Size([2, 3, 4])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) torch.Size([2, 4, 5])
tensor([[[ 6.,  6.,  6.,  6.,  6.],
         [22., 22., 22., 22., 22.],
         [38., 38., 38., 38., 38.]],

        [[54., 54., 54., 54., 54.],
         [70., 70., 70., 70., 70.],
         [86., 86., 86., 86., 86.]]]) torch.Size([2, 3, 5])


In [33]:
# Hadamard Product

print(A)
print(B)

print(A * B)    # A and B have same shape, calculate element-wise product

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


## Statistics

In [34]:
# Sum of all elements

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A, A.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor(190.))

In [35]:
# Sum by Dimension

X = torch.arange(24).reshape(2, 3, 4)
X, X.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 torch.Size([2, 3, 4]))

In [36]:
print(X.sum(axis=0))  # axis=0 --> eliminate the first dimension
print(X.sum(axis=0).shape)

print(X.sum(axis=1))  # axis=1 --> eliminate the second dimension
print(X.sum(axis=1).shape)

print(X.sum(axis=2))  # axis=2 --> eliminate the third dimension
print(X.sum(axis=2).shape)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
torch.Size([3, 4])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
torch.Size([2, 4])
tensor([[ 6, 22, 38],
        [54, 70, 86]])
torch.Size([2, 3])


In [37]:
# Sum by multiple dimensions: 

print(X)
print(X.shape)

print(X.sum(axis=[0, 1]))  # axis = 0 & 1 --> eliminate the first & second dimension
print(X.sum(axis=[0, 1]).shape)

print(X.sum(axis=[1, 2]))  # axis = 1 & 2 --> eliminate the second & third dimension
print(X.sum(axis=[1, 2]).shape)

print(X.sum(axis=[0, 2]))  # axis = 0 & 2 --> eliminate the first & third dimension
print(X.sum(axis=[0, 2]).shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor([60, 66, 72, 78])
torch.Size([4])
tensor([ 66, 210])
torch.Size([2])
tensor([ 60,  92, 124])
torch.Size([3])


In [38]:
# Calculate Statistics of Tensor

print(A.mean())
print(A.sum() / A.numel())

tensor(9.5000)
tensor(9.5000)


In [39]:
# Calculate Statistics by Axis

print(A, A.shape)
print(A.mean(axis=0))     # calculate mean along axis=0, eliminate axis=0 (first dimension)
print(A.sum(axis=0)/A.shape[0])   # same effect as above line
print(A.mean(axis=1))     # calcualte mean along axis=1, eliminate axis=1 (second dimension)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) torch.Size([5, 4])
tensor([ 8.,  9., 10., 11.])
tensor([ 8.,  9., 10., 11.])
tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000])


In [40]:
# Cumulative Sum

print(A)
print(A.cumsum(axis=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


## Broadcast

In [41]:
print(A)
print(A.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4])


In [42]:
sum_A = A.sum(axis=1, keepdims=True)  # sum up each row (axis=1), keep the rows=5 and column=1
print(sum_A)                          # has same number of dimensions with original tensor A
print(sum_A.shape)                    # 5x1 can be used for broadcast to the original tensor 5x4

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
torch.Size([5, 1])


In [43]:
A / sum_A   # divide each element by it's row's sum

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [44]:
# False Example: 

print(A.sum(axis=1))        # only sum up by axis=1, # dimensions reduce by 1
print(A.sum(axis=1).shape)  # lose the column dimension, can't be used for broadcast as # dimensions changed

A / A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])
torch.Size([5])


RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1